[package]
name = "quickpg"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-unit = "1.0.4"
fs_extra = "1.2.0"
portpicker = "0.1.1"
rand = "0.8.5"
regex = "1.7.1"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
whoami = "1.3.0"
